# -*- coding: utf-8 -*-
"""Additional TARNAR blog seeds (voice-guide-31 … 80) for SEO-rich static pages."""

EXTRA_JA_SEEDS = []
_kw = [
    "滑舌と歯列の余白を意識した短文練習",
    "会議で声が刺さらない話し方の音量設計",
    "鼻呼吸と口呼吸を切り替えるタイミング",
    "声帯ポリープ疑いのときにやってはいけないこと",
    "リハーサルでの声出しの最小セット",
    "アカペラでの音程ドリル短時間版",
    "ヘッドボイスとファルセットの聞き分け練習",
    "マイクゲインと声量のバランス表を作る",
    "録音室での立ち位置と反響の関係",
    "ポッドキャスト向けの話し声トーン調整",
    "オンライン会議のマイク設定チェックリスト",
    "歌唱時の舌根の沈め方イメージ",
    "子音の破裂を抑えたソフトな語り",
    "語尾を落とさず明瞭に聞こせるコツ",
    "早口言葉を声に負担なくこなす段階",
    "声域移行点付近の母音統一",
    "ブレスノイズを減らすマイク角度",
    "リバーブ量と歌声の馴染ませ方",
    "デュエットで相手の声を邪魔しない音量",
    "トリオ以上でのハーモニー取りの順番",
    "バンドリハでのモニター依頼の伝え方",
    "ライブハウスでの客席との距離感",
    "アコースティックセットでのダイナミクス",
    "電子楽器との音量バランスの耳コピ",
    "ストリートライブでの風向きと声の飛び",
    "屋外フェスでの水分と塩分補給",
    "夏場の発声で気をつける喉の乾燥",
    "冬場の冷えによる声の硬さ対策",
    "花粉症シーズンの声のケア",
    "寝不足時に避けたい練習メニュー",
    "ジョギング後の発声はなぜ難しいか",
    "筋トレ直後の体幹と呼吸の関係",
    "ヨガの腹圧と歌唱の腹圧の違い",
    "姿勢が崩れた椅子での補正ストレッチ",
    "長時間運転後の首のリカバリー",
    "飛行機移動後の耳抜きと声の関係",
    "高海拔エリアでの歌唱の注意",
    "温泉地滞在と声帯粘膜の保湿",
    "カフェイン摂取量と声の震え",
    "糖分補給と高音域の感覚",
    "アルコール後24時間の発声リスク",
    "アレルギー薬と口渇の対策",
    "鼻うがいと鼻腔共鳴のクリア感",
    "イヤホンリスニングの音量上限目安",
    "耳鳴りを感じた日の練習中止基準",
    "インプロビゼーションでの声の遊び方",
    "ジャズスキャットの入り方練習",
    "ソウル系フィルに負けない母音",
    "ロックシャウトの翌日ケア",
    "メタル系歪み声の休息設計",
    "ミュージカル歌唱の台詞と歌の切替",
    "オペラ風発声を趣味で取り入れるときの限界",
    "合唱指揮者に伝えやすい自分の課題文",
    "オンラインレッスン画面の明るさと表情",
    "スマホ録画での歪みを減らす距離",
    "Bluetoothマイク遅延と合わせの工夫",
]
_en = [
    "Short drills for articulation and mouth space",
    "Meeting voice levels that do not feel sharp",
    "When to switch nose vs mouth breathing",
    "What to avoid if polyps are suspected",
    "Minimal warm-up set for rehearsals",
    "Short intonation drills for a cappella",
    "Hearing head voice vs falsetto",
    "A simple table for mic gain vs vocal level",
    "Standing position and room reflections",
    "Podcast speaking tone basics",
    "Mic checklist for video calls",
    "Imagery to relax the tongue root",
    "Softer consonants for narration",
    "Clear endings without dropping pitch",
    "Tongue twisters in gentle stages",
    "Unifying vowels near passaggio",
    "Mic angle to reduce breath noise",
    "Reverb amount that fits vocals",
    "Volume etiquette in duets",
    "Harmony order in trios and larger",
    "How to ask for monitor changes in band rehearsal",
    "Distance to the audience in live houses",
    "Dynamics in acoustic sets",
    "Balancing with electronic instruments",
    "Wind and projection for busking",
    "Hydration and electrolytes at summer festivals",
    "Dry throat risks in hot seasons",
    "Cold weather stiffness strategies",
    "Voice care during pollen season",
    "Practice items to skip when sleep-deprived",
    "Why phonation feels hard after jogging",
    "Core and breath after strength training",
    "Yoga core pressure vs singing support",
    "Chair posture fixes for long sessions",
    "Neck recovery after long drives",
    "Ear clearing after flights and singing",
    "Singing cautions at higher altitude",
    "Humidity and vocal folds in hot spring trips",
    "Caffeine and subtle tremor",
    "Sugar and high-note perception",
    "Vocal risk window within 24h after alcohol",
    "Dry mouth with allergy meds",
    "Nasal rinse and resonance clarity",
    "Safe headphone listening levels",
    "When to stop practice if ears ring",
    "Playful voice colors in improvisation",
    "Entry drills for jazz scat",
    "Vowels that survive soul fills",
    "Next-day care after rock shouting",
    "Rest design for harsh vocal styles",
    "Switching speech to song in musicals",
    "Hobby limits when borrowing opera tone",
    "One sentence to tell your conductor",
    "Lighting and face for online lessons",
    "Distance to reduce phone video distortion",
    "Bluetooth latency and timing tricks",
]
_ko = [
    "발음과 치열 여백을 활용한 짧은 연습",
    "회의에서 날카롭지 않게 들리는 음량 설계",
    "코·입 호흡 전환 타이밍",
    "성대 폴립 의심 시 피해야 할 것",
    "리허설 최소 보컬 워밍업",
    "아카펠라 짧은 음정 드릴",
    "헤드보이스와 팔세토 구분 듣기",
    "마이크 게인과 성량 밸런스 표",
    "녹음실 서 있는 위치와 잔향",
    "팟캐스트 말투 톤 조정",
    "화상 회의 마이크 점검",
    "혀 뿌리 내리는 이미지",
    "부드러운 자음 처리",
    "어미를 떨어뜨리지 않고 명료하게",
    "빠른 혀 놀림을 단계적으로",
    "패시지 근처 모음 통일",
    "호흡 잡음 줄이는 마이크 각도",
    "리버브와 보컬의 어울림",
    "듀엣에서 상대를 가리지 않는 볼륨",
    "3인 이상 화음 잡는 순서",
    "밴드 리허설 모니터 요청법",
    "라이브 하우스 관객 거리감",
    "어쿠스틱 세트 다이내믹스",
    "전자 악기와의 밸런스",
    "버스킹 바람과 전달",
    "야외 페스 수분·전해질",
    "여름철 목 건조 주의",
    "겨울철 성대 뻣뻣함 대응",
    "꽃가루 시즌 보이스 케어",
    "수면 부족일 피할 연습",
    "조깅 후 발성이 어려운 이유",
    "근력 운동 직후 코어와 호흡",
    "요가 복압과 노래 지지",
    "의자 자세 교정 스트레칭",
    "장거리 운전 후 목 회복",
    "비행 후 귀압과 목소리",
    "고해발 고지에서의 노래 주의",
    "온천지 체류와 점막 보습",
    "카페인과 미세 떨림",
    "당분과 고음 감각",
    "음주 후 24시간 내 리스크",
    "알레르기 약과 입마름",
    "코 세척과 공명감",
    "이어폰 청취 상한 가이드",
    "이명 느낄 때 연습 중단 기준",
    "즉흥에서 목소리 놀이",
    "재즈 스캣 진입 연습",
    "소울 필에 지지 않는 모음",
    "록 샤우팅 다음날 케어",
    "헤시 보컬 휴식 설계",
    "뮤지컬 대사와 노래 전환",
    "오페라 톤 취미 한계",
    "지휘자에게 전할 한 문장",
    "온라인 레슨 조명과 표정",
    "폰 촬영 왜곡 줄이는 거리",
    "블루투스 지연과 타이밍",
]
_zh = [
    "口齿与齿列空间的短文练习",
    "会议发言不刺耳的音量设计",
    "鼻口呼吸切换的时机",
    "怀疑声带息肉时应避免的做法",
    "排练最小热身组合",
    "阿卡贝拉短音准练习",
    "头声与假声的听辨",
    "麦克风增益与音量对照表",
    "录音室站位与反射",
    "播客说话的语气调整",
    "视频会议麦克风检查",
    "舌根下沉的想象练习",
    "更柔和的辅音叙述",
    "字尾清晰不塌的处理",
    "绕口令的分段练习",
    "换声点附近的母音统一",
    "减少喷麦的麦克风角度",
    "混响与人声的融合",
    "二重唱不压对方的音量",
    "三人以上合唱的和声顺序",
    "乐队排练如何沟通监听",
    "Livehouse与观众距离感",
    "原声套装的动态控制",
    "与电子乐器的音量平衡",
    "街演风向与声音投射",
    "户外音乐节补水与电解质",
    "夏季发声的咽喉干燥",
    "冬季声音发紧的对策",
    "花粉季嗓音护理",
    "睡眠不足时避免的练习",
    "慢跑后发声为何变难",
    "力量训练后的核心与呼吸",
    "瑜伽腹压与歌唱支撑差异",
    "久坐椅姿的拉伸修正",
    "长途驾驶后的颈部恢复",
    "飞行后耳压与嗓音",
    "高海拔歌唱注意",
    "温泉地停留与黏膜保湿",
    "咖啡因与细微颤抖",
    "糖分与高音感知",
    "饮酒后24小时内的风险",
    "抗过敏药与口干",
    "洗鼻与共鸣通透",
    "耳机聆听的安全音量",
    "耳鸣日的练习中止标准",
    "即兴里的声音玩法",
    "爵士拟声入门练习",
    "灵魂乐填充下的母音稳定",
    "摇滚嘶吼次日护理",
    "极端嗓的休息设计",
    "音乐剧台词与歌唱切换",
    "业余借用歌剧音色限度",
    "告诉指挥的一句话",
    "网课灯光与表情",
    "手机录像减少失真的距离",
    "蓝牙延迟与对拍技巧",
]

for i in range(50):
    n = 31 + i
    slug = f"voice-guide-{n:02d}"
    ja_t = _kw[i]
    intro = (
        "本稿は、AI TARNAR Voice School の学習導線として、自宅やスタジオですぐ試せる手順をまとめたものです。"
        "痛みや違和感がある場合は無理をせず、専門家への相談を優先してください。"
    )
    mid = (
        "まずは小さな声で形だけ確認し、数日かけて負荷を上げます。"
        "録音して客観的に聴くと改善点が見つかりやすく、継続のモチベーションにもつながります。"
    )
    tail = (
        "Japan Music Tourism の音楽ツーリズム文脈では、移動・宿泊・現場環境が声のコンディションに影響します。"
        "旅前後のケアもセットで設計すると、学びと体験の両方が安定します。"
    )
    ja_b = ja_t + "。" + intro + mid + tail
    EXTRA_JA_SEEDS.append((slug, ja_t, ja_b))

EXTRA_EN_TITLES = _en[:50]
EXTRA_KO_TITLES = _ko[:50]
EXTRA_ZH_TITLES = _zh[:50]
