# -*- coding: utf-8 -*-
"""TARNAR blog seeds voice-guide-81 … 130 (50 articles, 4-lang titles + SEO bodies)."""

# Japanese titles (one line each, 50)
JA_T_81 = [
    "DAWでボーカルテイクを整えるコンプレッション入門",
    "ピッチ補正を自然に聞かせるためのプリ録方針",
    "リファレンス曲の聴き込み方とメモの取り方",
    "メトロノームより「グルーヴ優先」のカウント練習",
    "二重母音を滑らかにする英語フレーズ練習",
    "韓国語の 받침を歌に乗せる息の切り方",
    "中国語の儿化音をメロディに馴染ませるコツ",
    "アコギ弾き語りでの声と弦のバランス",
    "ピアノ弾き語りでの左手音量と声の芯",
    "バイオリンと歌うときの音程合わせの耳",
    "サックスと歌うときの息のタイミング",
    "ドラムの裏拍に乗せたフレージング",
    "シンセパッドの中で声を浮かせるEQの考え方",
    "ループステーションでのレイヤー録りの順番",
    "ワイヤレスマイクの電池と受信アンテナの確認",
    "RF干渉が起きたときの切り分け手順",
    "耳栓をしたままのモニタリングのコツ",
    "イヤモニ外し演奏時の客席フィードバック対策",
    "屋外ステージの風切り音を抑えるマイク角度",
    "雨粒がマイクに当たるときのカバーと距離",
    "夏の屋外ライブ後の冷やしすぎないリカバリー",
    "冬の屋外ライブ前の指先と口唇の準備",
    "早朝ロケ収録での小声トーンの作り方",
    "夜間収録での声量と近所配慮のバランス",
    "ナレーション収録での「間」の設計",
    "CM尺15秒に収めるフレーズの削ぎ方",
    "30秒尺の自己紹介ボイスを磨く",
    "Audition用1分歌唱の曲選びと冒頭設計",
    "合唱オーディションでのパート志望の伝え方",
    "バンドオーディションでの自己PR30秒",
    "オンラインオーディションのカメラ位置と光",
    "二段ハモリの音程を外さない練習メニュー",
    "三段ハモリで中声パートを安定させるコツ",
    "カノン形式の遅れ入りで拍を取り続ける方法",
    "スイング8ビートの裏のりを身体で覚える",
    "シャッフルリズムの歌い出しの吸い方",
    "オッドメーター曲のカウントイン設計",
    "テンポチェンジ曲の前後で声の張りを揃える",
    "ダイナミクス記号だけで練習プランを作る",
    "クレッシェンド中の喉の締め付けを避ける",
    "デクレッシェンドで声量だけでなく明瞭さを保つ",
    "スタッカート歌詞を歌いつなぐブレス設計",
    "レガート台詞とスタッカート歌の切替",
    "フォルテからピアノへ戻るときの喉の高さ",
    "ピアニッシモでも芯を残す息の速さ",
    "録音後のデータ整理とバックアップの儀式",
    "クラウド共有時の命名規則と権限メモ",
    "共同制作でボーカルテイクを渡すチェックリスト",
    "リモートセッションでの遅延補正の打ち合わせ",
    "ライブアーカイブ動画から学ぶ自分の癖分析",
]

EN_T_81 = [
    "Compression basics for vocal takes in a DAW",
    "Natural pitch correction: print decisions before mixing",
    "How to study reference tracks and take notes",
    "Groove-first counting beyond the metronome",
    "Smoother English diphthongs in sung phrases",
    "Breath cuts around Korean 받침 in songs",
    "Mandarin erhua blending with melody lines",
    "Balancing voice and strings in acoustic guitar sets",
    "Left-hand piano volume vs vocal core when you sing and play",
    "Tuning ears when singing with violin",
    "Breath timing when singing with saxophone",
    "Phrasing on the backbeat with drums",
    "EQ ideas to float vocals over synth pads",
    "Layer order when looping live",
    "Wireless mic battery and antenna checks",
    "Troubleshooting RF interference quickly",
    "Monitoring with earplugs in loud rooms",
    "House feedback when you perform without in-ears",
    "Mic angle to reduce wind noise outdoors",
    "Rain on the grill: covers and distance",
    "Cool-down without over-chilling after summer outdoor gigs",
    "Lips and fingertips prep for cold outdoor shows",
    "Soft morning voice for dawn location shoots",
    "Night session volume vs neighbor-friendly levels",
    "Designing pauses in narration reads",
    "Trimming phrases to fit a 15-second spot",
    "Polishing a 30-second spoken intro reel",
    "Song choice and opening arc for a 1-minute audition",
    "Stating your choral part preference clearly",
    "A tight 30-second band audition pitch",
    "Camera and light for online auditions",
    "Staying in tune on two-part harmony drills",
    "Stabilizing the middle voice in three-part stacks",
    "Keeping time while staggered entries in a canon",
    "Feeling swing eighths in the body first",
    "Breath pickups on shuffle grooves",
    "Planning count-ins for odd-meter tunes",
    "Matching vocal support before and after tempo jumps",
    "Practice plans using only dynamic markings",
    "Avoiding throat squeeze on long crescendos",
    "Keeping clarity while decrescendo",
    "Breath planning across staccato lyric lines",
    "Switching legato speech to staccato singing",
    "Vocal height when moving forte to piano",
    "Core in pianissimo without going breathy",
    "Post-recording file hygiene and backups",
    "Naming and permissions when sharing stems",
    "Checklist before handing off vocal stems",
    "Latency alignment talk for remote sessions",
    "Learning your habits from live archive footage",
]

KO_T_81 = [
    "DAW 보컬 테이크 컴프레션 입문",
    "자연스러운 피치 보정을 위한 프리프린트",
    "레퍼런스 곡 듣기와 메모법",
    "메트로놈보다 그루브 우선 카운트",
    "부드러운 영어 이중모음 연습",
    "한국어 받침 호흡 끊기",
    "중국어 er화와 멜로디",
    "어쿠스틱 기타와 보컬 밸런스",
    "피아노 반주와 왼손 볼륨",
    "바이올린과의 음정 맞추기",
    "색소폰과의 호흡 타이밍",
    "드럼 백비트 프레이징",
    "신스 패드 위 보컬 EQ",
    "루프스테이션 레이어 순서",
    "무선 마이크 배터리·안테나 점검",
    "RF 간섭 트러블슈팅",
    "이어플러그 모니터링",
    "인이어 없는 공연의 하울링",
    "야외 마이크 바람 각도",
    "비 맞는 그릴 대응",
    "여름 야외 후 과냉 방지",
    "겨울 야외 입술·손가락 준비",
    "새벽 로케 작은 목소리",
    "야간 녹음 이웃 배려",
    "내레이션 쉼 설계",
    "15초 CM 길이 다듬기",
    "30초 자기소개 보이스",
    "1분 오디션 곡 선정",
    "합창 오디션 파트 표현",
    "밴드 오디션 30초 PR",
    "온라인 오디션 카메라·조명",
    "2성부 하모니 연습",
    "3성부 중성 안정",
    "카논 박자 유지",
    "스윙 8분음표 몸으로",
    "셔플 리듬 들숨",
    "홀드박 템포 체인지",
    "다이나믹 기호만으로 연습표",
    "크레센도 목 압박 줄이기",
    "데크레센도 명료도 유지",
    "스타카토 가사 호흡",
    "레가토 대사와 스타카토 노래",
    "포르테→피아노 성대 높이",
    "피아니시모 코어",
    "녹음 후 파일 정리",
    "클라우드 공유 네이밍",
    "보컬 스템 넘기기 체크",
    "원격 세션 지연 맞추기",
    "라이브 아카이브로 습관 분석",
    "여행 일정에 끼워 넣는 보컬 워밍업",
]

ZH_T_81 = [
    "DAW人声压缩入门",
    "自然修音的预录策略",
    "参考曲聆听与笔记法",
    "优先律动的数拍练习",
    "英语双元音连唱",
    "韩语收音与换气",
    "儿化音与旋律融合",
    "木吉他弹唱音量平衡",
    "钢琴弹唱左手与人声",
    "与小提琴合唱的音准",
    "与萨克斯的呼吸配合",
    "贴合鼓反拍的乐句",
    "铺底合成器上的人声EQ",
    "循环工作站分层顺序",
    "无线麦克电池与天线",
    "射频干扰排查",
    "戴耳塞监听",
    "无耳返与啸叫",
    "户外防风麦克风角度",
    "雨滴打在网罩时",
    "夏日户外后不过度受凉",
    "冬季户外唇指准备",
    "清晨外拍小声线",
    "夜间录音与邻里",
    "旁白停顿设计",
    "15秒广告文案删减",
    "30秒自我介绍声线",
    "一分钟试音选曲",
    "合唱试音声部表达",
    "乐队试音30秒PR",
    "线上试音机位与光",
    "二部和声稳定练习",
    "三部中声部稳住",
    "卡农错位保持拍子",
    "摇摆八分身体先行",
    "Shuffle起拍吸气",
    "奇数拍导入设计",
    "变速前后支撑一致",
    "只用力度记号排练习",
    "渐强时避免喉挤",
    "渐弱保持清晰",
    "断奏歌词换气",
    "连说与断唱切换",
    "强到弱的喉位",
    "极弱仍有芯",
    "录音后文件整理",
    "云共享命名与权限",
    "交人声分轨前检查",
    "远程会话延迟对齐",
    "从现场录像看习惯",
]

BATCH2_JA_SEEDS: list[tuple[str, str, str]] = []
for i in range(50):
    n = 81 + i
    slug = f"voice-guide-{n:02d}"
    ja_t = JA_T_81[i]
    ja_b = (
        f"{ja_t}。"
        "AI TARNAR Voice School の実践ガイドとして、短いセッションで形を作り、録音で前後比較できる手順にしています。"
        "旅・公演・収録のリズムに合わせてメニューを差し替えられるよう、チェック項目は最小限に絞りました。"
    )
    BATCH2_JA_SEEDS.append((slug, ja_t, ja_b))

BATCH2_EN_TITLES = EN_T_81
BATCH2_KO_TITLES = KO_T_81
BATCH2_ZH_TITLES = ZH_T_81
